[CI] Fix the build scripts for new sharp

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -8,6 +8,8 @@ env:
   netBuildConfiguration: "Release"
   sharpName: "CCModManager.Sharp"
 
+
+# TODO: CLEAN UP!!!! THERE'S SO MUCH SHIT WE DON'T NEED ANYMORE
 jobs:
   build:
     runs-on: ${{ matrix.imageName }}
@@ -33,7 +35,7 @@ jobs:
             agentArch: "macOS"
             artifactPrefix: "macos."
             artifactSuffix: ""
-            netbuilder: "mono"
+            netbuilder: "core"
             monokickURL: "https://github.com/flibitijibibo/MonoKickstart.git"
             lualibs: "luarocks"
             luarocksPreArgs: "--lua-dir=/usr/local/opt/lua@5.1"
@@ -49,7 +51,7 @@ jobs:
             agentArch: "linux"
             artifactPrefix: "linux."
             artifactSuffix: ""
-            netbuilder: "mono"
+            netbuilder: "core"
             monokickURL: "https://github.com/flibitijibibo/MonoKickstart.git"
             lualibs: "luarocks"
             luarocksArgs: 'LUA_LIBDIR="/usr/local/opt/lua/lib"'
@@ -229,28 +231,19 @@ jobs:
         shell: bash
         run: |
           shopt -s extglob
-          cp -rv sharp/bin/**/!(xunit.*|System.*|Microsoft.*|*.Tests.dll|*.pdb) love/${{ matrix.loveBinaryDirectory }}/sharp
-          rm -rf love/${{ matrix.loveBinaryDirectory }}/sharp/net452
-          cp -rv sharp/bin/**/net452/* love/${{ matrix.loveBinaryDirectory }}/sharp
+          mkdir love/${{ matrix.loveBinaryDirectory }}/sharp || true
+          cp -rv sharp/bin/**/net6/!(xunit.*|System.*|Microsoft.*|*.Tests.dll|*.pdb) love/${{ matrix.loveBinaryDirectory }}/sharp
+      - name: "Dist: Fix UNIX sharp binary name"
+        if: ${{ success() && (matrix.agentArch == 'linux' || matrix.agentArch == 'macOS') }}
+        shell: bash
+        run: |
+          mv love/${{ matrix.loveBinaryDirectory }}/sharp/${{ env.sharpName }} love/${{ matrix.loveBinaryDirectory }}/sharp/${{ env.sharpName }}.bin.x86_64
+      - name: "Dist: Fix Windows sharp binary name"
+        if: ${{ success() && matrix.agentArch == 'windows' }}
+        shell: bash
+        run: |
+          mv love/${{ matrix.loveBinaryDirectory }}/sharp/${{ env.sharpName }}.exe love/${{ matrix.loveBinaryDirectory }}/sharp/${{ env.sharpName }}.bin.x86_64
       # }}}
-      # If needed, grab MonoKickstart and shove the prebuilts into the sharp dir. {{{
-      # Clone.
-      - name: "Dist: Clone MonoKickstart"
-        if: ${{ success() && matrix.monokickURL != '' }}
-        run: |
-          git clone ${{ matrix.monokickURL }}
-      - name: "Dist: Fix MonoKickstart"
-        if: ${{ success() && matrix.monokickURL != '' }}
-        shell: pwsh
-        run: |
-          Move-Item -Path MonoKickstart/precompiled/kick.bin.osx -Destination MonoKickstart/precompiled/${{ env.sharpName }}.bin.osx
-          Move-Item -Path MonoKickstart/precompiled/kick.bin.x86_64 -Destination MonoKickstart/precompiled/${{ env.sharpName }}.bin.x86_64
-          Remove-Item -Path MonoKickstart/precompiled/kick.bin.x86_64.debug -Force
-      # Copy the precompiled folder into the sharp folder.
-      - name: "Dist: Copy MonoKickstart"
-        if: ${{ success() && matrix.monokickURL != '' }}
-        run: |
-          cp -rv MonoKickstart/precompiled/* love/${{ matrix.loveBinaryDirectory }}/sharp
       # Copy special additional mono dependencies.
       # Those usually come from Ubuntu Mono packages with a version close to the MonoKickstart version.
       - name: "Dist: Copy prebuilt mono libs"
@@ -258,7 +251,6 @@ jobs:
         shell: bash
         run: |
           cp -rv lib-mono/* love/${{ matrix.loveBinaryDirectory }}/sharp
-      # }}}
       # Per-platform bundling steps. {{{
       - name: "Dist: Create artifact staging directories"
         run: |
@@ -307,7 +299,8 @@ jobs:
           cp ccmodmanager.sh love/${{ matrix.loveBinaryDirectory }}/ccmodmanager.sh
           chmod a+rx love/${{ matrix.loveBinaryDirectory }}/ccmodmanager.sh
           chmod a+rx love/${{ matrix.loveBinaryDirectory }}/love
-          chmod a+rx love/${{ matrix.loveBinaryDirectory }}/sharp/${{ env.sharpName }}.bin*
+          chmod a+rx love/${{ matrix.loveBinaryDirectory }}/sharp/${{ env.sharpName }}.bin.x86_64
+          chmod a+rx love/${{ matrix.loveBinaryDirectory }}/sharp/${{ env.sharpName }}.dll
           codesign --remove-signature love/${{ matrix.loveBinaryDirectory }}/love
           mv love/love.app love/CCModManager.app
           mkdir -p ../a/main
@@ -318,11 +311,13 @@ jobs:
       - name: "Dist: Linux: Finish"
         if: ${{ success() && matrix.agentArch == 'linux' }}
         run: |
+          ls love/sharp
           cp -v ccmodmanager.sh love/${{ matrix.loveBinaryDirectory }}/ccmodmanager
           chmod a+rx love/${{ matrix.loveBinaryDirectory }}/ccmodmanager
           chmod a+rx love/${{ matrix.loveBinaryDirectory }}/love
           chmod a+rx love/${{ matrix.loveBinaryDirectory }}/install.sh
-          chmod a+rx love/${{ matrix.loveBinaryDirectory }}/sharp/${{ env.sharpName }}.bin*
+          chmod a+rx love/${{ matrix.loveBinaryDirectory }}/sharp/${{ env.sharpName }}.bin.x86_64
+          chmod a+rx love/${{ matrix.loveBinaryDirectory }}/sharp/${{ env.sharpName }}.dll
           cp -v src/data/icon.png love/${{ matrix.loveBinaryDirectory }}/ccmodmanager.png
           rm -v love/${{ matrix.loveBinaryDirectory }}/lib/x86_64-linux-gnu/libz.so.1
           rm -v love/${{ matrix.loveBinaryDirectory }}/usr/lib/x86_64-linux-gnu/libfreetype.so.6
